export const CREATE_TASK = "CREATE_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const GET_TASKS = "GET_TASKS";

export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";

export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";
export const UPDATE_STATUS_FAILURE = "UPDATE_STATUS_FAILURE";
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

export const OPEN_EDIT_TASK = "OPEN_EDIT_TASK";
export const CLOSE_EDIT_TASK = "CLOSE_EDIT_TASK";
