export const LOGGING_IN = "LOGGING_IN";
export const LOGGED_IN = "LOGGED_IN";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const FETCH_INTRO = "FETCHING_INTRO";
export const FETCHED_INTRO = "FETCHED_INTRO";
export const INTRO_ERROR = "INTRO_ERROR";

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const FETCH_LOGGED_IN_USER_DETAILS = "FETCH_LOGGED_IN_USER_DETAILS";
export const FETCH_LOGGED_IN_USER_DETAILS_SUCCESS =
  "FETCH_LOGGED_IN_USER_DETAILS_SUCCESS";
export const FETCH_LOGGED_IN_USER_DETAILS_FAILURE =
  "FETCH_LOGGED_IN_USER_DETAILS_FAILURE";
